without ${PIPESTATUS[0]}

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -60,15 +60,15 @@ stages:
               # go test -v -coverprofile=coverage.txt -covermode count ./... 2>&1 | tee test_results.txt # stdout and stderr to terminal and to file --> perhaps identificaton of an error
               go test -v -coverprofile=coverage.txt -covermode count ./...
 
-              rc=${PIPESTATUS[0]} # Get result code of `go test`
+#              rc=${PIPESTATUS[0]} # Get result code of `go test`
               echo $rc
               $GOPATH/bin/gocov convert coverage.txt > coverage.json
               $GOPATH/bin/gocov-xml < coverage.json > coverage.xml
               # Check if `go test` had an error
-              if [ $rc -ne 0 ]; then  # if rc is not equal to 0
-                # Let script fail by writing to stderr
-                >&2 echo "Tests failed oh no"
-              fi
+#              if [ $rc -ne 0 ]; then  # if rc is not equal to 0
+#                # Let script fail by writing to stderr
+#                >&2 echo "Tests failed oh no"
+#              fi
 
               touch test_results.txt
 
